### ISSUE TITLE
Datový model

### ISSUE THREAD

**Issue by cerevka** [cerevka/Bookcase#25]
Nakreslit diagram tříd, alespoň 5 entit, zahrnout i integritní omezení a vztahy mezi nimi.

**Comment by cerevka** [comment]
Datový model zahrnuje zatím zahrnuje pouze základní funkcionalitu. Následně ho bude třeba rozšířit, bude-li to požadovat integrace.

Návrh na rozšíření:
- vlastnictví knihy
  - uživatel ji vlastní fyzicky
  - uživatel ji nevlastní fyzicky
- vztah uživatele ke knize
  - chci si přečíst
  - přečteno
  - nedotčeno
  - nepřečteno

**Comment by cerevka** [comment]
Obě rozšíření doplněna přes dekompozici. Doplněny enumy.

**Comment by PetrVales** [comment]
Navrhuji vynechani stavu NOT_READ z enumu EnumReadStatus (a kdyz uz v tom budes, tak mit v nazvum "Enum" nebo "E" se v dnestni dobe povazuje za prebytecne :) ), vyjadruje to podle me to same jako TO_READ (pomynuli dosti podivnej stav, ze bych si do sve knihovny pridal knihu, kterou jsem nikdy necetl a nemam v umyslu ji cist)

**Comment by cerevka** [comment]
K názvům:
Abys nebyl nepříjemně překvapen, až otevřeš kód, tak tě upozorním předem. Na tomhle projektu jsme s Adamem dělali experiment v konvenci pojmenovávání. A to tak, že každý objekt udává svůj typ a to POZPÁTKU... takže jsou "BeanSessionUser", "BeanManagedUser", "EntityUser", takže dle této konvence jsem vytvořil i "EnumReadState" :-). Krátké názvy považuji za zbytečné, vzhledem k tomu, že 90% psaní obstará našeptávač. A svým typem začínají proto, že když píšeš, tak přece víš jako první, jestli chceš entitu sesion beanu či manageged beanu (atd.).

Pak k těm stavům:
Může to znít zbytečně, ale představ si situaci, když třeba pod stromeček dostaneš knížku, která se ti vůbec nelíbí a neplánuješ ji tedy číst. Pak si ji zařadíš do knihovny, aby si ji ostatní mohli třeba půjčit, ale označíš si jí "NOT_READ".

Zkusim rozepsat všechny stavy:
READ - Přečteno.
TO_READ - K přečtení (v podstatě wishlist).
NOT_READ - Nepřečteno. (viz. výše)
READING - Rozečteno
NOT_FINISHED - Nedočteno (na lepší překlad jsem nepřišel). Rozečteš knižku, nelíbí se ti, nebo ji musíš odložit, protože na to nemáš čas, tak si ji označíš tutím.

**Comment by cerevka** [comment]
Vlastně mě ještě napadá, tak "NOT_READ" je implicitní volba, dokud nenastavíš jinak. Když ji vyřadíme, tak ji stejně nahradí nějaký NULL. To už mi připadá lepší takhle.

**Comment by PetrVales** [comment]
no to mam hroznou radost v vase experiment :) souhlasim s tim, ze kratke nazvy jsou blbost... ale davat tam i typ je na muj vkus prehnane, typ ti napovi IDE stejne jako dlouhej nazev :) ... no, budu se s tim muset smirit :) nebo to zrefaktorovat, ale to je moc velka drina :D

stalo ten stav povazuji za zbytecne :) , ale zavedu ho tam stavoveho diagramu jako inicialni stav, at se to nemuzi menit v kodu a nedohadujem se nad zbytecnostma :)

**Comment by cerevka** [comment]
Já myslím, že to je v pohodě. Nedělalo mi větší problém v tom psát a šlo to rychle. Ale chce to tu konvenci dodržovat, když už je zavedená ;-).

Když bude zbytečný, tak ho nikdo nebude používat a je to :-). Ale mám raději, když jsou pokryté všechny možnosti, než počítat s tím, že tohle nebude třeba.
Jinak takhle část tam ještě není. Tohle je přidaná funkcionalita do tohoto semestru. Je to docela hodně obohaceno, ale nemělo by to být složité to tam přidat.
