### ISSUE TITLE
Model procesů

### ISSUE THREAD

**Issue by cerevka** [cerevka/Bookcase#26]
Diagram aktivit, stavový diagram. Alespoň tři procesy z požadavků.

**Comment by PetrVales** [comment]
Přijímám případné připomínky, ještě jsem tu aplikaci nevidel, tak snad jsem to alespon priblizne trefil ...

**Comment by cerevka** [comment]
Vypadá to dobře, tohle bude určitě vyhovovat, díky :-).

Během tohoto týdne tu aplikací nasadím na server, jinak si ji můžeš zkusit nasadit na localhosta (akorát e-maily nebudou fungovat, ta schránka už neexistuje).

... jenom mám pocit, že v těch instrukcích pro nastavení Glassfishe, kdybys to chtěl zkoušl, se ztratilo nějaké vytvoření poolu. Ale už nevím kterého :-D. To zjistil cvičící při odevzdávání a když už jsme to Ačko mělo, tak se nikdo k opravě neměl :-D.
