### ISSUE TITLE
Stav knihy

### ISSUE THREAD

**Issue by cerevka** [cerevka/Bookcase#33]
Doimplementovat stav knih: rozečteno, přečteno... atd.

S tím souvisí i vlastnictví knihy - změna vztahu k poličkám.

**Comment by PetrVales** [comment]
pushnul jsem funkcni, ale neuplnou verzi, at tu mame pred pulnoci revizi na kterou se muzeme odvolat...

momentalne v seznamu vsech knih, si mohu priradit kteroukoliv z nich mezi sve (vytvori se copie a vlastnictvi), a ve svych knihach si je pak mohu prohlidnout - zatim nemuzu zmenit status precteni

mozna jsem to udelal trosku jinak, nez jste to puvodne zamysleli, ale snad to nebude tolik vadit

**Comment by cerevka** [comment]
Koukám, že se začaly projevovat Wokna :-D. V těch diffech to vypadá, jako kdybys všechno smazal a znovu vytvořil - hádám, že Windows předělaly konce řádků z Linuxových na ty svoje debilní :-D. No, to je fuk.

Původně to bylo myšleno tak, že Copy (ve smyslu svazku) se nebude kopírovat pro každého uživatele. Bylo to myšleno následovně:
Book = Je abstraktní objekt knihy ve smyslu nehmotného autorského díla.
Copy = Je konkrétním vydáním dané knihy s jednoznačným ISBN, vydavatelem a rokem vydání.
A vlastnictví knihy se udává před dekompoziční entity Ownership, tedy ve skutečnosti by to mělo vypadat tak, že více uživatelů vlastní jeden svazek (ve skutečnosti to představuje to, že mají svazek ze stejné šarže tisku).

Tak jaks to udělal ty to je samozřejmě také možné, ale pak je ta entity Ownership poněkud zbytečná a její logika by se dala přesunout přímo do Copy, ale pak se to tam těmi Copy začalo nepříjemně množim, přičemž všechny budou obsahovat to samé (vydavatel, rok vydání...).

**Comment by PetrVales** [comment]
Ja to udelal ve smyslu, ze Copy reprezentuje vytisk knihy. Taky jsem si puvodne myslel, ze Ownrship, by byla zbytecna, ale pokud uvazime, ze svuj vytisk mohu nekomu prodat, tak by Ownership (po pripadnem doplneni datumu) vyjadroval, kdy jsem dany vytisk vlastnil :) 
Jinak, az dnes jsem zjistil, ze se odevzdava az ve stredu o pulnoci :D

**Comment by cerevka** [comment]
Samozřejmě, i to je další výhoda, která se tam dá zapracovat :-). Já jsem při návrhu bral hlavně ohled na to, aby ta těch "Copy" nebylo zbytečně moc, což by přineslo nepřehlednost hlavně kvůli ISBN a vydavatelům. Ta dekompozice to sice trochu zesložiťuje, ale přijde mi, že to pak lépe dodržuje normální formy.

Jo, hoši, jako kdybych nevytvářel ty milestony :-D.

**Comment by cerevka** [comment]
Knihu si nyní sice můžu přidat do svých, ale kam zmizelo to "Vložit do košíku"?

**Comment by PetrVales** [comment]
To tam ted neni :D Nejak jsem nevidel, k cemu by jsme ted ten kosik potrebovali...

**Comment by cerevka** [comment]
Třeba k tomu, aby šlo vytvářet výpůjčky. Jinak to docela ztrácí smysl.

**Comment by cerevka** [comment]
Předělal jsem to na jednoduchou volbu pomocí selektu. Do budoucna bych to rád přes Ajax, nyní zcela postačuje. Zavírám.
