### ISSUE TITLE
Rozšíření rolí

### ISSUE THREAD

**Issue by cerevka** [cerevka/Bookcase#35]
Z původních rolí "user" a "admin" rozšířit na "user", "librarian", "administrator".

**Comment by PetrVales** [comment]
admina necham pojmenovaneho adminem, rekl bych, ze neni duvod to menit 
musel bych vsude vyskyt te role prepsat (to jsem linej)

**Comment by cerevka** [comment]
Jo, to klidně tak může zůstat.
Hlavně až to budeš pushovat, tak merguj... žádné force push. Tím bys přepsal to, co jsme tam doteď udělali.

**Comment by PetrVales** [comment]
todle je hotove, jen je potreba pridat si do DB zaznam s knihovnikem

zadnej force push nedelam, to kurvi git, driv fungoval normalne (nebo teda, mozna to delal ten git co byl v NB, uz jsem ho radsi prestal pouzivat)
