### ISSUE TITLE
Lze si přidat knihu, kterou již vlastním

### ISSUE THREAD

**Issue by cerevka** [cerevka/Bookcase#37]
Ve výpisu všech knih zobrazovat tlačítko pro přidání knihy do knihovničky jen tehdy, pokud knihu již nevlastním. Je tam na to funkce isBookOwnedByUser (či tak nějak) v BeanManagedBook (či tak nějak).

**Comment by PetrVales** [comment]
co jsem tak narychlo videl, tak jsme to tam ted pridali oba, nechal jsem tvou verzi

**Comment by cerevka** [comment]
Model výpůjček a svazků jsem zcela předělával, takže to je možné.
