### ISSUE TITLE
Hodnocení knih

### ISSUE THREAD

**Issue by cerevka** [cerevka/Bookcase#40]
Přidat možnost hodnotit knihy (v entitě Book).

**Comment by Ciselnak** [comment]
hotovo...vyjma pár drobností

**Comment by Ciselnak** [comment]
přidal jsem ošetření vícenásobnýho hodnocení a ošetřil nepřihlášenýho uživatele, trochu sem zpřehlednil výpisy hodnocení (i když je to pořád hnusný) a podle logiky že ani u přátelství jsem neimplementoval smazání přátelství tak ani tady neimplementuju smazání hodnocení (nebo změnu). nebo to mam naimplementovat šéfe? :-)
