### ISSUE TITLE
Zmena stavu precteni se neuklada do DB

### ISSUE THREAD

**Issue by PetrVales** [cerevka/Bookcase#42]
Zmena stavu precteni se neuklada do DB
-   nejak jsem si navykl automatickemu ukladani entit, takze jsem todle narychlo nevykoumal

**Comment by cerevka** [comment]
Automatické ukládání entit je nějakou speciální vlastností Springu, nebo se to musí jen někde zapnout a já nevím kde?

**Comment by cerevka** [comment]
Vyřešeno přes listener, nějak jsem to udělal během toho mergování. Hotovo.
