### ISSUE TITLE
Opravit Git a s nim i posledni commit

### ISSUE THREAD

**Issue by PetrVales** [cerevka/Bookcase#43]
Opravit Git a s nim i posledni commit

**Comment by cerevka** [comment]
Veškeré mergovani udělám já.
Dokud to nebude, nic s kódem nedělejte, pak se jen aktualizujete.
Příště žádné divné merge! Před pushem se testuje funkčnost projektu na localhostu a kontroluje se diff!
Za žádnou cenu se nesmí merge odbýt a musí se dělat, jinak to odstaví všechny!
