### ISSUE TITLE
Opravit kód po poslednim merge

### ISSUE THREAD

**Issue by Ciselnak** [cerevka/Bookcase#45]
jelikož jsem zrovna mergoval svoje změny a tomášovýma když petr comitoval (a nemergoval!!) musel jsem chtě nechtě zmergovat i petrovo změny proti tomášovým. ten kod sem neznal takže sem tam povětšinou nechal všechny metody od obou (EntityCopyXEntityPrint a podobně). Vašim úkolem je teď stáhnout si aktuální verzi a sjednotit se ve svych změnách. Na můj kód nesahejte ten by měl být OK.

jen pro informaci kód jde momentálně zbuildovat a po přegenerování databáze (která bude momentálně hodně redundantní) by měl teoreticky i fungovat, ale to jsem nezkoušel

**Comment by cerevka** [comment]
Veškeré mergovani udělám já.
Dokud to nebude, nic s kódem nedělejte, pak se jen aktualizujete.
Příště žádné divné merge! Před pushem se testuje funkčnost projektu na localhostu a kontroluje se diff!
Za žádnou cenu se nesmí merge odbýt a musí se dělat, jinak to odstaví všechny!
