### ISSUE TITLE
WS select Hodnocení knihy

### ISSUE THREAD

**Issue by cerevka** [cerevka/Bookcase#46]

**Comment by Ciselnak** [comment]
momentálně vracim hodnocení jako Integer ve formě TEXT_PLAIN,

**Comment by PetrVales** [comment]
Nemelo by tam byt spis "book/{isbn}/rating"? Aby to tvorilo nejakou hierarchii "book/{isbn}/name", "book/{isbn}/price", "book/{isbn}/author"... Mozna je to pouze muj uhel pohledu, rad prijmu protiargumenty :)

**Comment by Ciselnak** [comment]
souhlasim.... mě nenapadlo se na to koukat z hlediska tý hierarchie...předělam to jak říkáš je to tak logičtější

**Comment by cerevka** [comment]
Já to taky navrhoval jako jednu z možností v dnešní diskuzi v metru, ale Adam si vybral tohle.
Asi jsem neargumentoval ani, ale přišlo mi to tak taky lepší. Dobrý argument.
