### ISSUE TITLE
WS create Vytvoření knihy

### ISSUE THREAD

**Issue by cerevka** [cerevka/Bookcase#48]

**Comment by PetrVales** [comment]
Pridal jsem do war-ka Jersey REST-framework (ten co se s nim pracoval na cviku). Pracovalo se s nim celkem v pohode a nic jineho neznam. Pokud nekdo z vas zna neco lepsi, tak to vcas navrhnete :)

**Comment by cerevka** [comment]
Také jsem chtěl použít Jersey, neb jsem zatím nic jiného stejně nepoznal :-).

**Comment by cerevka** [comment]
Připomínám, že WS je třeba dodělat dneska tak do osmi večer, abych to stihnul nasadit na produkční stroj. Nebudu to zase dělat o půlnoci.

Pak doplň na wiki parametry služby dle toho, jak jsi ji navrhnul.

**Comment by PetrVales** [comment]
Pamatuji na to, tahnu se dnes s notebookem jen kvuli tomu ;) :)

**Comment by PetrVales** [comment]
- Ok, hotovo. Wiki si jeste jednou projdu vecer, az se vratim z plavani.
- V kodu jsem upravil zobrazeni datumu vydani na cele datum. Pokud nekde na wiki uvadite ze tam je pouze rok, tak to opravte.

**Comment by cerevka** [comment]
Ok, super - měl bych pár připomínek:

1) Na přednášce teď v pondělí bylo uváděno, že pro vytváření nových zdrojů se má používat metoda POST. Metodu PUT sice taky připoštěl, ale že už to není tak košér. PUT se používá pro aktualizace.

2) Na té samé přednášce uvádět, že při úspěšném vytvoření nového zdroje se má vracet návratový kód 201 (Created), nikoliv obyčejná 200 (OK).

3) S tím datem vydání to je tak, že všude pracuji jen s rokem. Při vytváření knihy se zadává jen rok, při exportu XML s informace o knize udávám pouze rok. Ono se to celé datum nikde nepoužívá, jak jsem koukal.

**Comment by PetrVales** [comment]
PUT zmenen na POST
vracim 201 + entitu v xml
xml obsahuje jak rok tak i datum (pokud je nekde jen rok, tak by to melo dat k zacatku roku) - komrpomis, uz to nechci vic rozkopavat

**Comment by cerevka** [comment]
Ať na to koukám, jak koukám, a ať to zkouším, jak zkouším, tak stále nic... tohle podle mě snad ani nemůže fungovat... a pokud ano, tak se ten kód určitě nechová tak, jak jsi to popsal v dokumentaci.

Testoval jsi to vůbec?

Vůbec mi není jasné, jak se má napasovat to XML do toho parametru new Book, když tam nikde nemáš žádnou mapovací anotaci na ten request (nějaký @FormParam), dále dle dokumentace vůbec není řečeno, jak se ten POSTovej parametr má jmenovat - jestli to je myšleno jako tělo stránky, tak pak se mi žádným restovým klientem nepodařilo správně vložit - a myslím, že pak by to kompletně porušovalo restový princip. Postová data se přenášejí v postové hlavičce, nikde tam nic takového nemáš.

Dále máš v dokumentaci, že se vrací ta entita v XML, ale dle kódu se tak neděje a ani se dít nemůže - ty tam vracíč jen nějaký objekt Response, ve kterém sestavuješ uri, na kterém bude nový zdroj dostupný, což mi přijde v pořádku. Ale pak to přece nevrací XML, jaks uvedl na wiki.

**Comment by PetrVales** [comment]
data se prikladaji do tela requstu (snad to neni v rosporu s nejakym z mnoha pravidel restu - RESTovy klient to dovoluje) - mozna bych to mel presneji uvest na wiki

do odpovedi prida xml 
response =Response.created(new URI( baseUri.toString() + "rest/book/" + newBook.isbn))
                     .entity(getBook(newBook.isbn))    // tento radek
                     .build();

**Comment by cerevka** [comment]
Já jsem zkoušel dva RESTové klienty, kteří byli pouze jako plugin do Chrome. To, že se to dává do těla, mě napadlo, ale žádný z těch klientů to neumožňoval (nebo alespoň mě se to nepodařilo, zkoušel jsem i prázdnou řádku před tím a nic).
Jestli to je korektní z hlediska RESTu, netuším. Můžeme se zeptat na cvičení.

Toho jsem si nevšiml, že se k tomu dává i ten objekt, proto mi to bylo zvláštní. Vypadalo to, že se vrací jen url k vytvořenému zdroji.

Tak to se omlouvám, díky za vysvětlení.

**Comment by PetrVales** [comment]
Ja pouzivm ten klient, co nam ho doporucil na cviceni

Snad je to z pohledu RESTu v poradku, aby to bylo v tele zpravy ... 

Jeste to opravim na wiki, at je to z toho popisu jasnejsi
