### ISSUE TITLE
Role knihovníka do autoconfigu.

### ISSUE THREAD

**Issue by cerevka** [cerevka/Bookcase#50]
Do inicializace databáze přidat roli knihovníka.

**Comment by PetrVales** [comment]
Mel jsem chvilku casu, tak jsem to tam pridal. Reknete mi nekdo, kdybych porad spatne commitoval CRLF - alespon si to mohu vyzkouset na male zmene kodu.

**Comment by cerevka** [comment]
Vypadá to už dobře... poznáš to podle toho, že když si rozklikneš commit, tak v něm jdou pěkně vidět všechny změnu: 
https://github.com/cerevka/Bookcase/commit/80af9c05e451c6e2f98eab925c3f1cf077113b0e

Kdyby ten soubor vypadal, jako kdybys ho celý smazal a znovy vytvořil, tak by to bylo špatně :-).
