### ISSUE TITLE
Integrovat vyhledávání knih

### ISSUE THREAD

**Issue by cerevka** [cerevka/Bookcase#54]
Projekt fulltextový vyhledávač (https://edux.fit.cvut.cz/courses/MI-MDW/team/101t2/web_services_design_implementation_deployment_testing)

**Comment by cerevka** [comment]
Nejdříve musí být realizování vkládání do vyhledávače (#53), jinak to nic nenajde.
Pak stačí přidat input pro fulltextové vyhledávání ke stávajícímu vyhledávání, zavolat službu a zobrazit výsledky:
- Titul knihy
- Odkaz na detail knihy
- (perex - myslím, že ten to vrátí taky)

Řešit vše na jedné stránce, dělit to do více view nemá smysl.

**Comment by Ciselnak** [comment]
takže moje část je hotová. Teď se pokaždý když je přidána kniha k nám do databáze pomocí GUI přidá se i do fulltextovýho vyhledávání - dělá to metoda addBookToFulltextSearch. 
Všechno co musíš udělat je přidat input na fulltextový vyhledávání na naší vyhledávací stránku. Potom už použiješ službu našich kolegú. Nejdřív je třeba se k nim přihlásit, pak použiješ službu POST /search/ (v popisu maji špatně port ve skutečnosti běží na portu 3000) lang nastavíš na cs a jméno schématu je "books" a pak se odhlásíš. Jako data ti ta funkce vrátí tag ve kterym je url nalezený knihy v naší aplikci a ještě něco ale to asi nebudeš potřebovat
username i heslo na přihlášení k nim je "bookcase".
kdyby něco klidně se ptej...možná sem zapomněl na něco podstatnýho

**Comment by PetrVales** [comment]
ok hotovo...  snad :)
dal jsem to vyhledavani pod to tlacitko co tam bylo...
takze nejdriv vypise primou shodu a podtim vysledky z fulltextoveho vyhledavani

ta komunikace se servisou asi mela byt nejakym zmusobem stavova, aby jsme se porad neprihlasovali a neodhlasovali (na webu to taky nedelame), tak jsme si meli drzet cookies (a znovu se logovat az v momente, kdy jim vyprsi platnost), aby jsme tim snizili komunikacni overhead - ale rozhodne to nebudu predelavat kdyz uz jsme to udelali takle, stejne je to pro skolni projekt uplne jedno :)

**Comment by cerevka** [comment]
Tak jasně, bylo by to lepší, ale shodli jsme se s Adamam na tom, že se nám to řešit opravdu nechce :-D. 

Perfektní, takže o Kybernalitě to nasadím na produkční server. Jenom ještě prosímtě doplň na wiki nějak popis použití té služby.
